# fly.toml app configuration file generated for znvo-backend-purple-water-2340 on 2023-12-06T16:00:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "znvo-backend-purple-water-2340"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "40000"

[http_service]
  internal_port = 40000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
